### ISSUE TITLE
assets input -> output not supported

### ISSUE THREAD

**Issue by jere2101** [Coly010/ng-rspack-build#17]
Hi, 

i tested the ng-rspack-build package with an existing Project that's currently using the angular application builder. 
And i get problems using the assets input -> output options. 

Is this currently not supported or is their are way to achive the same behaviour. 
 
My Config:
![image](https://github.com/user-attachments/assets/d31d6c8c-d4df-40d6-8bb5-3b9a14904cfe)

Error:
![image](https://github.com/user-attachments/assets/8ef1cf8c-f7ed-4175-8fa6-fe3ee64319e2)

And thanks for your work on this project, very cool.

**Comment by Coly010** [comment]
It's not supported yet :) It's already been listed as Known Issue 7 here: https://github.com/Coly010/ng-rspack-build/issues/7#issue-2553676940

If you want to take a stab at implementing it, feel free to open a PR :)
