### ISSUE TITLE
Feature Request: Custom Rspack Config

### ISSUE THREAD

**Issue by eilensm** [Coly010/ng-rspack-build#20]
Hi, is it possible or do you plan to support module federation? As far as I understand module federation documentation I would need to add the module federation plugin to the rspack.config. But it seems you dynamically generate one...

Any help/info is appreciated!

Kind regards,
Marc

**Comment by Coly010** [comment]
Yes the plan is it to support Module Federation.

It will be supported via an option to provide a custom Rspack config that will be merged with the config that is generated dynamically.

**Comment by Coly010** [comment]
Added by #21 !
