### ISSUE TITLE
Inconsistent Attribute Naming: options instead of _options in NgRspackModuleFederationPlugin

### ISSUE THREAD

**Issue by swalker326** [Coly010/ng-rspack-build#25]
### Description 
I found an inconsistency in the attribute naming for NgRspackModuleFederationPlugin. This plugin returns an attribute named options, while other plugins following the Module Federation standard return _options. This difference breaks compatibility in workflows or tools that depend on the consistent use of _options.

### Expected Behavior
The NgRspackModuleFederationPlugin should return _options to align with the standard naming convention used by other Module Federation plugins, such as RspackModuleFederationPlugin.

### Current Behavior

Currently, NgRspackModuleFederationPlugin returns:

```
MF Entry NgRspackModuleFederationPlugin {
  options: {
    // other attributes
  }
}
```
While other plugins like RspackModuleFederationPlugin return:

```
MF Entry ModuleFederationPlugin {
  _options: {
    // other attributes
  }
}
```
### Suggested Solution
Rename the options attribute in NgRspackModuleFederationPlugin to _options to ensure consistent attribute naming across plugins in compliance with the Module Federation standard.

### Impact
This inconsistency causes issues when using NgRspackModuleFederationPlugin alongside other plugins that rely on the _options attribute.

**Comment by Coly010** [comment]
The options don’t usually get exposed to the User, hence the `_` prefix for the other MFPs. 

What use case are you following that requires you to touch the internal options object in the plugin class?

**Comment by swalker326** [comment]
> The options don’t usually get exposed to the User, hence the `_` prefix for the other MFPs.
> 
> What use case are you following that requires you to touch the internal options object in the plugin class?
> 
> and in other words, by explaining, it can let me think about what could be done that would aid in that use case if it deems it.

We wrap the rspack/webpack/vite config with our plugin then access the `_options` attribute to replace local URLs  ie.`localhost:8080` with deployed dev urls. It enables us to only spin up one project locally and still have access to any other apps needed to work on the project.

**Comment by Coly010** [comment]
Ok, I think in this case just renaming the options to _options makes the most sense

**Comment by swalker326** [comment]
> Ok, I think in this case just renaming the options to _options makes the most sense

Awesome, I opened a PR. If you see anything I'm missing I can address it with a little guidance 😄 just let me.
